language: node_js
node_js:
  - 12
  - node
  - lts/*
before_script:
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - npm run build
script:
  - npm test
  - npm run test-browser
addons:
  chrome: stable
