jobs:
  include:
    - language: node_js
      node_js:
        - 12
        - node
        - lts/*
      before_script:
        - npm run build
    - language: node_js
      node_js:
        - node
      before_script:
        - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
      script:
        - npm run test-browser
      addons:
        chrome: stable

