language: node_js
node_js:
  - 12
  - lts/*
  - node
jobs:
  include:
    - name: npm test
      before_script:
        - npm run build
  exclude:
    - name: npm run test-browser
      node_js: node
      script:
        - CHROME_PATH="google-chrome-stable" npm run test-browser
      addons:
        chrome: stable

