language: node_js
before_script:
  - npm run build
jobs:
  include:
    - name: npm test
      node_js: 12
    - name: npm test
      node_js: lts/*
    - name: npm test
      node_js: node
    - name: npm run test-browser
      node_js: node
      script:
        - CHROME_PATH="google-chrome-stable" npm run test-browser
      addons:
        chrome: stable

