language: node_js
node_js:
  - node
jobs:
  include:
    - node_js:
        - 12
        - node
        - lts/*
      before_script:
        - npm run build
    - script:
        - CHROME_PATH="google-chrome-stable" npm run test-browser
      addons:
        chrome: stable

