version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout
workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/

