version: 2.1
orbs:
  node: circleci/node@5.00
jobs:
  test:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - run:
          command: |
            npm run build 
            npm run test
workflows:
  test:
    jobs:
      - test
