name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm test
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'tsertkov@users.noreply.github.com'
          git tag \
            -a "v${{ steps.publish.outputs.version }}" \
            -m "release-v${{ steps.publish.outputs.version }}"
          git push --tags
